name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Pull and Push Images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image Aliyun
      run: |
        while IFS= read -r line || [ -n "$line" ]; do
          num_slashes=$(echo "$line" | grep -c '/')
          if [[ $num_slashes == 2 ]]; then
            full_path=$line
            image_name=${full_path%%*/}
          elif [[ $num_slashes == 1 ]]; then
            full_path="docker.io/$line"
            image_name=${full_path%%*/}
          elif [[ $num_slashes == 1 ]]; then
            full_path="docker.io/library/$line"
            image_name=$line
          else
            echo ":("
          fi
          docker run --net=host quay.io/skopeo/stable:latest copy --debug --multi-arch all --dest-username $ALIYUN_REGISTRY_USER --dest-password $ALIYUN_REGISTRY_PASSWORD docker://$full_path docker://$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image_name
          docker system prune -f
        done < images.txt
