name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Pull and Push Images
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image Aliyun
      run: |
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        while IFS= read -r line || [ -n "$line" ]; do
          echo "Processing image: $line"
          
          # Process amd64 architecture
          echo "Pulling amd64 image..."
          docker pull --platform linux/amd64 $line
          image=$(echo "$line" | awk '{print $NF}')
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image"
          echo "Tagging amd64 image..."
          docker tag $image $new_image
          echo "Pushing amd64 image..."
          docker push $new_image
          echo "Removing local amd64 image..."
          docker rmi $image
          docker rmi $new_image
          
          # Process arm64 architecture
          echo "Pulling arm64 image..."
          docker pull --platform linux/arm64 $line
          image=$(echo "$line" | awk '{print $NF}')
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image"
          echo "Tagging arm64 image..."
          docker tag $image $new_image
          echo "Pushing arm64 image..."
          docker push $new_image
          echo "Removing local arm64 image..."
          docker rmi $image
          docker rmi $new_image
          
          echo "Starting disk cleanup..."
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
          docker rmi $image
          docker rmi $new_image
          echo "Disk space cleanup complete"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
        done < images.txt
